# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c37b561eb4f36f047f066e4b50ddf57f019ef1e93d83c2b70f57aee6e5ac7d535a3358cd266e190ca3ee0d153fc5c2248f7d543b0d23c4a2ddf2dfaccd34b47

test:
  secret_key_base: ca4d5fa91342ac8d8986fab7c81f24294848bffed4a5d41ff31a67b565a3d044b41e4aa41272718c577ba00700cbcf2bafaf723a9973e6b76b464a475a540c48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
